root: true
globals:
  chrome: true
env:
  browser: true
  es6: true

extends: eslint:recommended

parserOptions:
  sourceType: module
  requireConfigFile: false
  ecmaVersion: latest
  ecmaFeatures:
    modules: true
